### ISSUE TITLE
兄弟你好！

### ISSUE THREAD

**Issue by ManutdGTA** [chengirii/file-crypto#1]
兄弟你好！
我在这链接看到了你的回复
https://github.com/zksync-sdk/zksync-crypto-c/issues/9
但我不知道怎么引入这个.a文件，问了AI还是没解决，想问下大哥怎么解决的

**Comment by chengirii** [comment]
根据官方文档，需要在你的代码引用  https://docs.zksync.io/api/sdk/python/tutorial/#setup-crypto-library

**Comment by chengirii** [comment]
> 兄弟你好！ 我在这链接看到了你的回复 [zksync-sdk/zksync-crypto-c#9zksync-sdk/zksync-crypto-c#9](https://github.com/zksync-sdk/zksync-crypto-c/issues/9) 但我不知道怎么引入这个.a文件，问了AI还是没解决，想问下大哥怎么解决的

根据官方文档，需要在你的代码引用 https://docs.zksync.io/api/sdk/python/tutorial/#setup-crypto-library

**Comment by ManutdGTA** [comment]
谢谢兄弟，方便留个联系方式吗。我已经能用sdk，成功mint nft了。但现在在swap token上遇到了问题。文档里写需要传两个orders，例如我现在要把ETH换成USDC，但我不知道怎么传第二个orders。文档里写的很奇怪，我把submitter换成了wallet，但是第二个order不知道怎么获取，我只知道第一个order应该是我的ETH换成USDC的order


顺便说一声抱歉，找不到你的联系方式，只能在你的项目里提issue了
```
orderA = await walletA.get_order('USDT', 'ETH', Fraction(1500, 1), RatioType.token, Decimal('10.0'))
orderB = await walletB.get_order('ETH', 'USDT', Fraction(1, 1200), RatioType.token, Decimal('0.007'))
tx = await submitter.swap((orderA, orderB), 'ETH')
```

**Comment by chengirii** [comment]
> 谢谢兄弟，方便留个联系方式吗。我已经能用sdk，成功mint nft了。但现在在swap token上遇到了问题。文档里写需要传两个orders，例如我现在要把ETH换成USDC，但我不知道怎么传第二个orders。文档里写的很奇怪，我把submitter换成了wallet，但是第二个order不知道怎么获取，我只知道第一个order应该是我的ETH换成USDC的order
> 
> 顺便说一声抱歉，找不到你的联系方式，只能在你的项目里提issue了
> 
> ```
> orderA = await walletA.get_order('USDT', 'ETH', Fraction(1500, 1), RatioType.token, Decimal('10.0'))
> orderB = await walletB.get_order('ETH', 'USDT', Fraction(1, 1200), RatioType.token, Decimal('0.007'))
> tx = await submitter.swap((orderA, orderB), 'ETH')
> ```

请留下你的联系方式

**Comment by ManutdGTA** [comment]
> > 谢谢兄弟，方便留个联系方式吗。我已经能用sdk，成功mint nft了。但现在在swap token上遇到了问题。文档里写需要传两个orders，例如我现在要把ETH换成USDC，但我不知道怎么传第二个orders。文档里写的很奇怪，我把submitter换成了wallet，但是第二个order不知道怎么获取，我只知道第一个order应该是我的ETH换成USDC的order
> > 顺便说一声抱歉，找不到你的联系方式，只能在你的项目里提issue了
> > ```
> > orderA = await walletA.get_order('USDT', 'ETH', Fraction(1500, 1), RatioType.token, Decimal('10.0'))
> > orderB = await walletB.get_order('ETH', 'USDT', Fraction(1, 1200), RatioType.token, Decimal('0.007'))
> > tx = await submitter.swap((orderA, orderB), 'ETH')
> > ```
> 
> 请留下你的联系方式

微信 553464735
